# Generated by Django 3.2.11 on 2022-01-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('org', models.CharField(max_length=255)),
                ('space', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('complete', models.BooleanField(default=False, help_text="Do we have a full month's data?")),
                ('forecast', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage_change', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'billing_data',
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=255)),
                ('space', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddConstraint(
            model_name='billingdata',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'org', 'space'), name='unique entry'),
        ),
    ]
