# Generated by Django 2.2.6 on 2019-12-18 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDSCost',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GDSOrganization',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GDSOrganizationsSpace',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gds.GDSOrganization')),
            ],
        ),
        migrations.CreateModel(
            name='GDSForecast',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('difference', models.FloatField()),
                ('cost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gds.GDSCost')),
            ],
        ),
        migrations.AddField(
            model_name='gdscost',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gds.GDSOrganization'),
        ),
        migrations.AddField(
            model_name='gdscost',
            name='report_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportDate'),
        ),
        migrations.AddField(
            model_name='gdscost',
            name='space_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gds.GDSOrganizationsSpace'),
        ),
    ]
