# Generated by Django 2.2.6 on 2019-12-11 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GDSOrganization',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GDSReportDate',
            fields=[
                ('month', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GDSOrganizationsSpace',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gds.GDSOrganization')),
            ],
        ),
        migrations.CreateModel(
            name='GDSCost',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gds.GDSOrganization')),
                ('report_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gds.GDSReportDate')),
                ('space_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gds.GDSOrganizationsSpace')),
            ],
        ),
    ]
