# Generated by Django 2.2.6 on 2019-12-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdsorganization',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gdsorganizationsspace',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
