# Generated by Django 2.2.6 on 2019-12-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwsAccount',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AwsAccountCost',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aws.AwsAccount')),
                ('report_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportDate')),
            ],
        ),
        migrations.CreateModel(
            name='AwsForecast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('difference', models.FloatField()),
                ('cost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aws.AwsAccountCost')),
            ],
        ),
    ]
