# Generated by Django 2.2.6 on 2019-12-11 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwsReportDates',
            fields=[
                ('month', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Aws Report Dates',
            },
        ),
        migrations.CreateModel(
            name='AwsAccounts',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('report_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aws.AwsReportDates')),
            ],
            options={
                'verbose_name_plural': 'Aws Accounts',
            },
        ),
        migrations.CreateModel(
            name='AwsAccountCost',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aws.AwsAccounts')),
            ],
            options={
                'verbose_name_plural': 'Aws Account Cost',
            },
        ),
    ]
