# Generated by Django 2.2.6 on 2019-12-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwsAccounts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccountsCost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aws.AwsAccounts')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aws.AwsReportDates')),
            ],
        ),
    ]
